spring:

  application:
    name: blackjack-api

  data:
    mongodb:
      host: localhost
      port: 27017
      database: blackjack
      # username: your-username
      # password: your-password

  r2dbc:
    url: r2dbc:mysql://localhost:3306/blackjack
    # username: your-username
    # password: your-password

server:
    port: 8080